### ISSUE TITLE
gulp throws error

### ISSUE THREAD

**Issue by lsolesen** [zetagraph/monoset#13]
I after installing everything by ´npm install´, I tried the following:

```
codio@corona-mayday:~/workspace/drupal/web/themes/contrib/monoset$ gulp                                                                                                         
```

But I got the follwing error:

```
ReferenceError: Promise is not defined                                                                                                                                          
    at Object.<anonymous (/home/codio/workspace/drupal/web/themes/contrib/monoset/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/pleeease/node_modules/postcss-import/index.js:13:27)                                                                                                                                                     
    at Module._compile (module.js:456:26)                                                                                                                                       
    at Object.Module._extensions..js (module.js:474:10)                                                                                                                         
    at Module.load (module.js:356:32)                                                                                                                                           
    at Function.Module._load (module.js:312:12)                                                                                                                                 
    at Module.require (module.js:364:17)                                                                                                                                        
    at require (module.js:380:17)                                                                                                                                               
    at Object.<anonymous> (/home/codio/workspace/drupal/web/themes/contrib/monoset/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/pleeease/lib/processors.js:7:22)                                                                                                                                                                         
    at Module._compile (module.js:456:26)                                                                                                                                       
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by zetagraph** [comment]
@lsolesen what version of node (node --version) are you running? I have v0.12.7 and its fine here. I think I've seen the "Promise is not defined" error related to other stuff but it went away after node upgrade. You can also disable styleguide stuff to see if its related to that.

**Comment by lsolesen** [comment]
```
codio@corona-mayday:~/workspace$ node --version                                                                                                                                     
v0.10.33
```

**Comment by zetagraph** [comment]
@lsolesen see if you can upgrade your node, I think that should take care of the error.
